# Generated by Django 5.0 on 2023-12-29 20:41

import django.db.models.deletion
from django.db import migrations, models
from django.conf import settings

class Migration(migrations.Migration):
    initial = True

    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]

    operations = [
        migrations.CreateModel(
            name="Day",
            fields=[
                (
                    "number",
                    models.PositiveIntegerField(primary_key=True, serialize=False),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DayResolution",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("answer_part_one", models.CharField(max_length=1000)),
                ("answer_part_two", models.CharField(max_length=1000)),
                ("input", models.TextField()),
                (
                    "day",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="adventapi.day"
                    ),
                ),
            ],
        ),
    ]
