# Generated by Django 5.0 on 2023-12-29 18:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("adventapi", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dayresolution",
            name="user",
        ),
        migrations.AlterField(
            model_name="day",
            name="number",
            field=models.PositiveIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(25),
                ]
            ),
        ),
    ]
