# Generated by Django 5.0 on 2023-12-29 18:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("adventapi", "0002_remove_dayresolution_user_alter_day_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="day",
            name="number",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="dayresolution",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
