# Generated by Django 5.0 on 2024-01-15 16:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("adventapi", "0006_dayresolution_comment_reply"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dayresolution",
            name="code",
            field=models.CharField(max_length=100000),
        ),
    ]
