# Generated by Django 5.0 on 2024-01-16 18:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("adventapi", "0008_alter_customuser_groups_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dayresolution",
            name="comments_quantity",
            field=models.IntegerField(default=0),
        ),
    ]
