# Generated by Django 5.0 on 2024-01-17 18:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("adventapi", "0009_dayresolution_comments_quantity"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dayresolution",
            old_name="comment",
            new_name="description",
        ),
    ]
