# Generated by Django 5.0 on 2024-01-17 18:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("adventapi", "0010_rename_comment_dayresolution_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="dayresolution",
            name="link_to_repo",
            field=models.CharField(default="none", max_length=200),
            preserve_default=False,
        ),
    ]
