# Generated by Django 5.0 on 2024-01-22 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("advent_days", "0001_initial"),
        ("adventapi", "0015_dayresolution_likes_like"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dayresolution",
            name="day",
        ),
        migrations.RemoveField(
            model_name="dayresolution",
            name="language",
        ),
        migrations.RemoveField(
            model_name="dayresolution",
            name="user",
        ),
        migrations.AlterField(
            model_name="comment",
            name="resolution",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="advent_days.dayresolution",
            ),
        ),
        migrations.AlterField(
            model_name="recentresolutions",
            name="resolution",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="advent_days.dayresolution",
            ),
        ),
        migrations.AlterField(
            model_name="like",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="advent_days.dayresolution",
            ),
        ),
        migrations.DeleteModel(
            name="Day",
        ),
        migrations.DeleteModel(
            name="Language",
        ),
        migrations.DeleteModel(
            name="DayResolution",
        ),
    ]
