# Generated by Django 5.0 on 2024-01-26 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Day",
            fields=[
                (
                    "number",
                    models.PositiveIntegerField(primary_key=True, serialize=False),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="DayResolution",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("answer_part_one", models.CharField(max_length=1000)),
                ("answer_part_two", models.CharField(max_length=1000)),
                ("input", models.TextField()),
                ("code", models.CharField(max_length=100000)),
                ("description", models.TextField()),
                ("comments_quantity", models.IntegerField(default=0)),
                ("link_to_repo", models.CharField(default="none", max_length=200)),
                ("likes", models.IntegerField(default=0)),
                (
                    "day",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="advent_days.day",
                    ),
                ),
            ],
        ),
    ]
