# Generated by Django 5.0 on 2024-01-22 20:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("advent_days", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dayresolution",
            name="likes",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="dayresolution",
            name="link_to_repo",
            field=models.CharField(default="none", max_length=200),
        ),
    ]
