# Generated by Django 5.0 on 2024-01-23 19:19

from django.db import migrations

programming_languages = [
    "JavaScript", "Python", "Java", "C#", "C++", "TypeScript", "PHP", "Ruby", "Swift", "Go",
    "Kotlin", "Rust", "Objective-C", "Shell", "MATLAB", "R", "Scala", "Groovy", "Dart", "Perl",
    "HTML/CSS", "SQL", "MATLAB", "Lua", "Visual Basic", "Assembly Language", "Fortran", "Cobol",
    "PL/SQL", "Apex", "PowerShell", "Ada", "Lisp", "Haskell", "Clojure", "Julia", "Delphi",
    "ActionScript", "Scratch", "Blockly", "LabVIEW", "Prolog", "VHDL", "Verilog", "Erlang", "F#",
    "ABAP", "COOL", "Scheme", "Smalltalk"
]

def generate_programming_languages(apps, schema_editor):
    L = apps.get_model('advent_days', 'Language')
    for p in programming_languages:
        L.objects.create(name=p)

class Migration(migrations.Migration):
    dependencies = [
        ("advent_days", "0002_alter_dayresolution_likes_and_more"),
    ]

    operations = [migrations.RunPython(generate_programming_languages)]
