# Generated by Django 5.0 on 2024-01-26 20:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("advent_days", "0003_delete_python"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dayresolution",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
